// Code generated by goctl. DO NOT EDIT.
package types

type VersionResp struct {
	Version int64 `json:"Version"`
}

type BlogIdReq struct {
	ID string `path:"id"`
}

type BlogIdsReq struct {
	IDs []string `json:"ids"`
}

type BlogIdsResp struct {
	IDs []string `json:"ids"`
}

type BlogBriefResp struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	Tags       []string `json:"tags"`
	Brief      string   `json:"brief"`
	CreateTime uint64   `json:"c_time"`
}

type BlogDetailResp struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	Tags       []string `json:"tags"`
	Content    string   `json:"content"`
	CreateTime uint64   `json:"c_time"`
}

type ArchivesBlogIdsReq struct {
	Page int `path:"page"`
}

type ArchivesBlogIdsResp struct {
	BlogIdsResp *BlogIdsResp `json:"blogidsresp"`
	MaxPages    int          `json:"maxpages"`
}

type CollectionPageReq struct {
	Page int    `json:"page"`
	Name string `json:"name"`
}

type CollectionResp struct {
	Name  string   `json:"name"`
	Brief string   `json:"brief"`
	IDs   []string `json:"ids"`
}

type CollectionPageResp struct {
	MaxPages        int                   `json:"maxpages"`
	CollectionResps []*CollectionPageResp `json:"collectionsresps"`
}
