// Code generated by goctl. DO NOT EDIT.
package types

type ArchivesBlogIdsReq struct {
	Page int `path:"page"`
}

type ArchivesBlogIdsResp struct {
	IDs      []string `json:"ids"`
	MaxPages int      `json:"maxpages"`
}

type BlogBriefResp struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	Tags       []string `json:"tags"`
	Brief      string   `json:"brief"`
	CreateTime uint64   `json:"c_time"`
}

type BlogDetailResp struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	Tags       []string `json:"tags"`
	Content    string   `json:"content"`
	CreateTime uint64   `json:"c_time"`
}

type BlogIdReq struct {
	ID string `path:"id"`
}

type BlogIdsReq struct {
	IDs []string `json:"ids"`
}

type BlogIdsResp struct {
	IDs []string `json:"ids"`
}

type CollectionBriefReq struct {
	ID string `json:"name"`
}

type CollectionBriefResp struct {
	Name  string `json:"name"`
	Brief string `json:"brief"`
}

type CollectionLatestResp struct {
	IDs []string `json:"ids"`
}

type CollectionPageReq struct {
	Page int    `json:"page"`
	ID   string `json:"id"`
}

type CollectionPageResp struct {
	MaxPages int      `json:"maxpages"`
	IDs      []string `json:"ids"`
}

type VersionResp struct {
	Version int64 `json:"Version"`
}
