// Code generated by goctl. DO NOT EDIT.
package types

type BlogBriefResp struct {
	ID    string   `json:"id"`
	Tags  []string `json:"tags"`
	Brief string   `json:"brief"`
}

type BlogDetailResp struct {
	ID      string   `json:"id"`
	Tags    []string `json:"tags"`
	Content string   `json:"content"`
}

type BlogIdReq struct {
	ID string `path:"id"`
}

type BlogIdsReq struct {
	IDs []string `json:"ids"`
}

type VersionResp struct {
	Version int64 `json:"Version"`
}
