// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: host.proto

package host

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBlogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Tags    []string `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Brief   string   `protobuf:"bytes,3,opt,name=Brief,proto3" json:"Brief,omitempty"`
	Content string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *UploadBlogReq) Reset() {
	*x = UploadBlogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBlogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogReq) ProtoMessage() {}

func (x *UploadBlogReq) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogReq.ProtoReflect.Descriptor instead.
func (*UploadBlogReq) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBlogReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadBlogReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UploadBlogReq) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *UploadBlogReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UploadBlogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"` // 上传的博客的id
}

func (x *UploadBlogResp) Reset() {
	*x = UploadBlogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadBlogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogResp) ProtoMessage() {}

func (x *UploadBlogResp) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogResp.ProtoReflect.Descriptor instead.
func (*UploadBlogResp) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBlogResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UploadBlogResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadBlogResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBlogReq) Reset() {
	*x = DeleteBlogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogReq) ProtoMessage() {}

func (x *DeleteBlogReq) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogReq.ProtoReflect.Descriptor instead.
func (*DeleteBlogReq) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBlogReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteBlogResp) Reset() {
	*x = DeleteBlogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogResp) ProtoMessage() {}

func (x *DeleteBlogResp) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogResp.ProtoReflect.Descriptor instead.
func (*DeleteBlogResp) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBlogResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteBlogResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UploadPicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // `base64` or `url`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UploadPicReq) Reset() {
	*x = UploadPicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPicReq) ProtoMessage() {}

func (x *UploadPicReq) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPicReq.ProtoReflect.Descriptor instead.
func (*UploadPicReq) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{4}
}

func (x *UploadPicReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadPicReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UploadPicResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UploadPicResp) Reset() {
	*x = UploadPicResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPicResp) ProtoMessage() {}

func (x *UploadPicResp) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPicResp.ProtoReflect.Descriptor instead.
func (*UploadPicResp) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{5}
}

func (x *UploadPicResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UploadPicResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadPicResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DeletePicResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeletePicResp) Reset() {
	*x = DeletePicResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_host_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePicResp) ProtoMessage() {}

func (x *DeletePicResp) ProtoReflect() protoreflect.Message {
	mi := &file_host_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePicResp.ProtoReflect.Descriptor instead.
func (*DeletePicResp) Descriptor() ([]byte, []int) {
	return file_host_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePicResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeletePicResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_host_proto protoreflect.FileDescriptor

var file_host_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x22, 0x69, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x42, 0x72, 0x69, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x42, 0x72,
	0x69, 0x65, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a,
	0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3c, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x69,
	0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x39, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0x9e, 0x02, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x13, 0x2e, 0x68, 0x6f, 0x73, 0x74,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x12, 0x13, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x13, 0x2e, 0x68, 0x6f,
	0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x69, 0x63, 0x12, 0x12, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x50, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x09,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x63, 0x12, 0x13, 0x2e, 0x68, 0x6f, 0x73, 0x74,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_host_proto_rawDescOnce sync.Once
	file_host_proto_rawDescData = file_host_proto_rawDesc
)

func file_host_proto_rawDescGZIP() []byte {
	file_host_proto_rawDescOnce.Do(func() {
		file_host_proto_rawDescData = protoimpl.X.CompressGZIP(file_host_proto_rawDescData)
	})
	return file_host_proto_rawDescData
}

var file_host_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_host_proto_goTypes = []any{
	(*UploadBlogReq)(nil),  // 0: host.UploadBlogReq
	(*UploadBlogResp)(nil), // 1: host.UploadBlogResp
	(*DeleteBlogReq)(nil),  // 2: host.DeleteBlogReq
	(*DeleteBlogResp)(nil), // 3: host.DeleteBlogResp
	(*UploadPicReq)(nil),   // 4: host.UploadPicReq
	(*UploadPicResp)(nil),  // 5: host.UploadPicResp
	(*DeletePicResp)(nil),  // 6: host.DeletePicResp
}
var file_host_proto_depIdxs = []int32{
	0, // 0: host.Host.CreateBlog:input_type -> host.UploadBlogReq
	0, // 1: host.Host.UpdateBlog:input_type -> host.UploadBlogReq
	2, // 2: host.Host.DeleteBlog:input_type -> host.DeleteBlogReq
	4, // 3: host.Host.UploadPic:input_type -> host.UploadPicReq
	2, // 4: host.Host.DeletePic:input_type -> host.DeleteBlogReq
	1, // 5: host.Host.CreateBlog:output_type -> host.UploadBlogResp
	1, // 6: host.Host.UpdateBlog:output_type -> host.UploadBlogResp
	3, // 7: host.Host.DeleteBlog:output_type -> host.DeleteBlogResp
	5, // 8: host.Host.UploadPic:output_type -> host.UploadPicResp
	6, // 9: host.Host.DeletePic:output_type -> host.DeletePicResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_host_proto_init() }
func file_host_proto_init() {
	if File_host_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_host_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UploadBlogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UploadBlogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBlogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBlogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UploadPicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UploadPicResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_host_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeletePicResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_host_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_proto_goTypes,
		DependencyIndexes: file_host_proto_depIdxs,
		MessageInfos:      file_host_proto_msgTypes,
	}.Build()
	File_host_proto = out.File
	file_host_proto_rawDesc = nil
	file_host_proto_goTypes = nil
	file_host_proto_depIdxs = nil
}
