// Code generated by goctl. DO NOT EDIT.
// Source: host.proto

package server

import (
	"context"

	"host/internal/logic"
	"host/internal/svc"
	"host/pb/host"
)

type HostServer struct {
	svcCtx *svc.ServiceContext
	host.UnimplementedHostServer
}

func NewHostServer(svcCtx *svc.ServiceContext) *HostServer {
	return &HostServer{
		svcCtx: svcCtx,
	}
}

func (s *HostServer) CreateBlog(ctx context.Context, in *host.UploadBlogReq) (*host.UploadBlogResp, error) {
	l := logic.NewCreateBlogLogic(ctx, s.svcCtx)
	return l.CreateBlog(in)
}

func (s *HostServer) UpdateBlog(ctx context.Context, in *host.UploadBlogReq) (*host.UploadBlogResp, error) {
	l := logic.NewUpdateBlogLogic(ctx, s.svcCtx)
	return l.UpdateBlog(in)
}

func (s *HostServer) DeleteBlog(ctx context.Context, in *host.DeleteBlogReq) (*host.DeleteBlogResp, error) {
	l := logic.NewDeleteBlogLogic(ctx, s.svcCtx)
	return l.DeleteBlog(in)
}

func (s *HostServer) UploadPic(ctx context.Context, in *host.UploadPicReq) (*host.UploadPicResp, error) {
	l := logic.NewUploadPicLogic(ctx, s.svcCtx)
	return l.UploadPic(in)
}

func (s *HostServer) DeletePic(ctx context.Context, in *host.DeleteBlogReq) (*host.DeletePicResp, error) {
	l := logic.NewDeletePicLogic(ctx, s.svcCtx)
	return l.DeletePic(in)
}
